# Generated by Django 6.0.3 on 2026-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('starwars', 'LEGO Star Wars'), ('icons', 'LEGO Icons'), ('technic', 'LEGO Technic'), ('ideas', 'LEGO Ideas'), ('ninjago', 'LEGO Ninjago')], default='starwars', max_length=50),
        ),
    ]
